doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        types:
            redes.marca_switch:
                class:                App\DBAL\Type\Enum\Redes\MarcaSwitchType
            redes.status_vlan:
                class:                App\DBAL\Type\Enum\Redes\StatusVlanType
            redes.port_type:
                class:                App\DBAL\Type\Enum\Redes\PortTypeType
            redes.port_mode:
                class:                App\DBAL\Type\Enum\Redes\PortModeType
#        driver: 'pdo_mysql'
#        server_version: '5.7'
#        charset: utf8mb4
#        default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci
#
#        url: '%env(resolve:DATABASE_URL)%'
        connections:
            default:
                driver:   '%env(resolve:VOGEL_DRIVER)%'
                host:     '%env(resolve:VOGEL_HOST)%'
                port:     '%env(resolve:VOGEL_PORT)%'
                dbname:   '%env(resolve:VOGEL_DBNAME)%'
                user:     '%env(resolve:VOGEL_USER)%'
                password: '%env(resolve:VOGEL_PASSWORD)%'
                charset:  '%env(resolve:VOGEL_CHARSET)%'
                mapping_types:
                    marca_switch: redes.marca_switch
                    status_vlan: redes.status_vlan
                    port_type: redes.port_type
                    port_mode: redes.port_mode
            redes:
                driver:   '%env(resolve:VOGEL_DRIVER)%'
                host:     '%env(resolve:VOGEL_HOST)%'
                port:     '%env(resolve:VOGEL_PORT)%'
                dbname:   '%env(resolve:VOGEL_DBNAME)%'
                user:     '%env(resolve:VOGEL_USER)%'
                password: '%env(resolve:VOGEL_PASSWORD)%'
                charset:  '%env(resolve:VOGEL_CHARSET)%'
                mapping_types:
                    marca_switch: redes.marca_switch
                    status_vlan: redes.status_vlan
                    port_type: redes.port_type
                    port_mode: redes.port_mode
                schema_filter: '/^(redes.)/'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Entity'
                        alias: AppEntity
            redes:
                connection: redes
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Entity'
                        alias: AppEntity
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
