# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    cors:
        allowed_origin:
            - http://fast.local.com:3000
        allowed_headers:
            - AccessToken
            - Content-Type
            - AuthVersion
            - ApiKey
            - Cookie
            - Accept
            - Origin
            - Authorization
    sso:
        url_base: "http://sso.local.com"
        cookie_name: "sso"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

        
    App\Services\SSO\AuthExceptions:
        public: false
            
    auth_exception:
          class: App\Services\SSO\AuthExceptions
          public: true
        
    App\Services\SSO\SSoClient:
        public: false
            
    sso_client:
          class: App\Services\SSO\SSoClient
          public: true
        
    App\EventListener\SSOAuthEventListener:
        public: false
        arguments: ['%cors%', "@logger", "@auth_exception", "@sso_client"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }

    services.service:
          alias: App\Services\Service
          public: true

    App\Services\Service:
          public: false
          arguments: ["@doctrine", "@logger"]
          
          
    App\Controller\Service\ServiceController:
        arguments: ['@services.service', '@logger']

    services.switch_model:
          alias: App\Services\SwitchModel
          public: true

    App\Services\SwitchModel:
          public: false
          arguments: ["@doctrine", "@logger"]
          
          
    App\Controller\SwitchModel\SwitchModelController:
        arguments: ['@services.switch_model', '@logger']

    