post_pdv:
    path: /
    controller: 'App\Controller\Service\ServiceController::postService'
    methods: [POST]
    defaults:
        _format: json
        
get_pdv:
    path: /{idService}
    controller: 'App\Controller\Service\ServiceController::getService'
    methods: [GET]
    defaults:
        _format: json
    requirements:
        idService: '\d+'
        
list_pdv:
    path: /
    controller: 'App\Controller\Service\ServiceController::getServices'
    methods: [GET]
    defaults:
        _format: json
        
delete_pdv:
    path: /{idService}
    controller: 'App\Controller\Service\ServiceController::deleteService'
    methods: [DELETE]
    defaults:
        _format: json
    requirements:
        idService: '\d+'
        
put_pdv:
    path: /{idService}
    controller: 'App\Controller\Service\ServiceController::putService'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        idService: '\d+'
        
patch_pdv:
    path: /{idService}
    controller: 'App\Controller\Service\ServiceController::patchService'
    methods: [PATCH]
    defaults:
        _format: json
    requirements:
        idService: '\d+'
