post_switchs:
    path: /
    controller: 'App\Controller\Switchs\SwitchsController::postSwitchs'
    methods: [POST]
    defaults:
        _format: json
        
get_switchs:
    path: /{idSwitchs}
    controller: 'App\Controller\Switchs\SwitchsController::getSwitchs'
    methods: [GET]
    defaults:
        _format: json
    requirements:
        idSwitchs: '\d+'
        
        
list_switchs:
    path: /
    controller: 'App\Controller\Switchs\SwitchsController::getSwitchss'
    methods: [GET]
    defaults:
        _format: json
        
delete_switchs:
    path: /{idSwitchs}
    controller: 'App\Controller\Switchs\SwitchsController::deleteSwitchs'
    methods: [DELETE]
    defaults:
        _format: json
    requirements:
        idSwitchs: '\d+'
        
put_switchs:
    path: /{idSwitchs}
    controller: 'App\Controller\Switchs\SwitchsController::putSwitchs'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        idSwitchs: '\d+'
        
patch_switchs:
    path: /{idSwitchs}
    controller: 'App\Controller\Switchs\SwitchsController::patchSwitchs'
    methods: [PATCH]
    defaults:
        _format: json
    requirements:
        idSwitchs: '\d+'
