App\Entity\Redes\Switchs:
    type: entity
    table: redes.switchs
    indexes:
        IDX_25D50C753BDF040:
            columns:
                - pop_id
        IDX_25D50C75BC0921E:
            columns:
                - switch_model_id
        IDX_25D50C78B4937A1:
            columns:
                - vlan_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: true
        createdAt:
            type: datetime
            nullable: false
            options:
                default: now()
            column: created_at
        removedAt:
            type: datetime
            nullable: true
            column: removed_at
        addressIpv4:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: address_ipv4
        addressIpv6:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: address_ipv6
        username:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        community:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        modifiedAt:
            type: datetime
            nullable: true
            column: modified_at
    manyToOne:
        pop:
            targetEntity: App\Entity\Redes\Pop
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pop_id:
                    referencedColumnName: id
            orphanRemoval: false
        switchModel:
            targetEntity: App\Entity\Redes\SwitchModel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                switch_model_id:
                    referencedColumnName: id
            orphanRemoval: false
        vlan:
            targetEntity: App\Entity\Redes\Vlan
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                vlan_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        port:
            targetEntity: App\Entity\Redes\Port
            orderBy:
                type: ASC
                numbering: ASC
            cascade:
                - persist
                - merge
                - remove
            fetch: LAZY
            mappedBy: switchs
    lifecycleCallbacks: {  }
