App\Entity\Redes\SwitchModelPort:
    type: entity
    table: redes.switch_model_port
    indexes:
        IDX_53CDCFAB5BC0921E:
            columns:
                - switch_model_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        portType:
            type: redes.port_type
            nullable: false
            column: port_type
        quantities:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        switchModel:
            targetEntity: App\Entity\Redes\SwitchModel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                switch_model_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
